url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Alexis Fabre" # the name of your site, e.g. ACME Corp.
email: hello@alexisfabre.fr
twitter_username: narbonnais_
github_username:  narbonnais
job: Lead offensive security engineer
markdown: kramdown
